### ISSUE TITLE
Please help 🙏🏻

### ISSUE THREAD

**Issue by SourcingDenis** [brett-hobbs/coda-lever-sync#5]
Hi mate. I am trying to set this up - and having no luck, unfortunately. Can you quickly guide me through this? 🙏  I appreciate your time!

**Comment by brett-hobbs** [comment]
Any specific issue?

I'd recommend just using the Pack now that it exists: https://coda.io/packs/lever

I wrote this before the pack existed but I've since switched to the pack.
